apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-notification-service.fullname" . }}
  labels:
    {{- include "todo-notification-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.websocket.enabled }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: websocket
    {{- end }}
  selector:
    {{- include "todo-notification-service.selectorLabels" . | nindent 4 }}
